### PR TITLE
Safer updateToOreDictRecipes

### PR DESCRIPTION
**Pull request by elifoster**
Throwing exceptions makes me sad when method overloading can be used instead.

### CODE REVIEW

**Comment by Zenith-One** [comment]
This code is actually dead at the moment anyway. I don't need it anymore now that my pull request made it in. It didn't work in the first place, really.

**Comment by elifoster** [comment]
Never mind then. I was just browsing the code and found an unneeded throw. Didn't really pay attention to its context aside from the context of the throw. Heh.

**Comment by Zenith-One** [comment]
I wouldn't necessarily have closed it. That said, I throw errors when incorrect arguments are passed into things, so that it fails loudly and informatively. And as soon as possible. Mostly comes from being burned by not doing so in my day job.

I can see the merit in the way your code works though. I'll try and remember that going forward.

**Comment by elifoster** [comment]
Throwing errors caused by an incorrect argument type in a statically typed language is weird and somewhat pointless. IMO it's better to just overload the possibly dangerous private method with safer public versions.

Also, I didn't really see the point in keeping the branch around if the code is dead :P

**Comment by Zenith-One** [comment]
Yeah, I blame that habit on the fact that I spend all day working in javascript where overloading isn't a thing you can do. :)

**Comment by elifoster** [comment]
Yeah I understand that, I work with Ruby a lot which A) doesn't support overloading, and B) is dynamically typed. However, Ruby will throw errors for you when the method won't work for the type anyway. Not sure about JS as I tend to avoid it at all costs.

**Pull request closed without merging**
